name: Deploy main branch to Pantheon

concurrency:
  group: ${{ github.workflow }}-main
  cancel-in-progress: false

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      deployments: write
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Push to Pantheon
      uses: pantheon-systems/push-to-pantheon@0.5.0
      with:
        ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
        machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
        site: ${{ vars.PANTHEON_SITE }}
        delete_old_environments: true
